In [2]:
import numpy as np
from numpy.random import randn

In [3]:
np.set_printoptions(precision=2)

In [10]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
b = np.array([[40,50,60],[10,20,30]])
b

array([[40, 50, 60],
       [10, 20, 30]])

In [9]:
np.random.seed(25)
c=36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [11]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [12]:
a * 10

array([10, 20, 30, 40, 50, 60])

In [17]:
c + a
c - a
c * a
c / a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

In [18]:
aa = np.array([[2,4,6],[1,3,5],[10,20,30]])
aa

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [10, 20, 30]])

In [19]:
bb = np.array([[0,1,2],[1,3,5],[6,7,8]])
bb

array([[0, 1, 2],
       [1, 3, 5],
       [6, 7, 8]])

In [20]:
aa*bb

array([[  0,   4,  12],
       [  1,   9,  25],
       [ 60, 140, 240]])

In [21]:
np.dot(aa,bb)

array([[ 40,  56,  72],
       [ 33,  45,  57],
       [200, 280, 360]])